lints.workspace = true

[package]
name = "numeric-static-iter"
version = "0.1.0"
edition = "2021"

[features]
alloc = ["numeric-traits/alloc"]
std = ["numeric-traits/std", "alloc"]

[dependencies]
numeric-traits = { path = "../traits", default-features = false }
